#!/bin/bash

PYECLOUDPATH=../../../
CURRDIR=/afs/cern.ch/work/e/ecldcode/sim_workspace_PyHEADTAIL_3/LHC_dip_instab_simulations/simulations/HLLHC-injection_ArcDip_edens10.00e11_inten1.3e11_rep02
export CURRDIR

source /afs/cern.ch/work/k/kli/public/venv_py27_slc6/bin/activate
which python

PYTHONPATH=$PYECLOUDPATH
export PYTHONPATH
echo $PYTHONPATH


cd ${CURRDIR}

#execute simulation
python 000_instability_simulation_with_kick.py


